# Generated by Django 4.0.5 on 2022-06-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('wi_id', models.AutoField(primary_key=True, serialize=False)),
                ('wi_name', models.CharField(max_length=100, verbose_name='Name')),
                ('wi_image', models.ImageField(null=True, upload_to='images/', verbose_name='Image')),
                ('wi_descrip', models.TextField(null=True, verbose_name='Description')),
            ],
        ),
    ]
